# https://taskfile.dev

version: "3"

vars:
  TAG: v0.0.1-dev0

tasks:
  local-build:
    cmds:
      - go build ./cmd/d8-doc-ru-linter
  build:
    cmds:
      - werf build --repo docker.io/fl64/d8-doc-ru-linter --add-custom-tag={{ .TAG }}
